sys:
  # ログイン画面フッター文字
  login_footer: ''
  # 携帯向けフッター文字
  mobile_footer: ''
  # セッション保持期限（H）
  session_expiration: 24
  # 携帯向けセッション保持期限（H）
  session_expiration_for_mobile: 1
  # PCサイト/携帯サイト強制表示
  force_site: ''
  # ファイル名変換UserAgent
  file_encode_prefix: 'MSIE,Trident'
  # 初期パスワードでのログイン禁止
  refuse_initial_password: off
  # ドラッグアンドドロップによるファイルアップロード
  fileupload_with_drag_and_drop: on
