#!/bin/sh
#
# chkconfig: - 99 20
# description: delayed_job start/stop script

set -e
APP_PATH="/var/share/jorurigw"
APP_USER="joruri"
APP_ENV="production"

start_job() {
  echo "Starting delayed job"
  su -l $APP_USER -c "cd ${APP_PATH}; RAILS_ENV=${APP_ENV} bin/delayed_job start"
}

stop_job() {
  echo "Stopping delayed job"
  su -l $APP_USER -c "cd ${APP_PATH}; RAILS_ENV=${APP_ENV} bin/delayed_job stop"
}

COMMAND="$1"
shift

case $COMMAND in
status)
  ;;
start|stop|restart)
  $ECHO
  if [ "$COMMAND" = "stop" ]; then
    stop_job
  elif [ "$COMMAND" = "start" ]; then
    start_job
  elif [ "$COMMAND" = "restart" ]; then
    stop_job
    sleep 1s
    start_job
    exit 0
  fi
  ;;
esac
