class CreateGwboardTables < ActiveRecord::Migration
  def change
    # gwbbs
    create_table "gwbbs_categories" do |t|
      t.integer  "unid"
      t.integer  "parent_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.integer  "title_id"
      t.integer  "sort_no"
      t.integer  "level_no"
      t.text     "name"
    end
    create_table "gwbbs_comments" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "doc_type"
      t.integer  "parent_id"
      t.text     "content_state"
      t.integer  "title_id"
      t.text     "name"
      t.text     "pname"
      t.text     "title"
      t.text     "head",               limit: 16777215
      t.text     "body",               limit: 16777215
      t.text     "note",               limit: 16777215
      t.integer  "category1_id"
      t.integer  "category2_id"
      t.integer  "category3_id"
      t.integer  "category4_id"
      t.text     "keyword1"
      t.text     "keyword2"
      t.text     "keyword3"
      t.text     "keywords"
      t.text     "createdate"
      t.string   "createrdivision_id", limit: 20
      t.text     "createrdivision"
      t.string   "creater_id",         limit: 20
      t.text     "creater"
      t.text     "editdate"
      t.string   "editordivision_id",  limit: 20
      t.text     "editordivision"
      t.string   "editor_id",          limit: 20
      t.text     "editor"
      t.datetime "expiry_date"
      t.text     "inpfld_001"
      t.text     "inpfld_002"
    end
    create_table "gwbbs_db_files" do |t|
      t.integer "title_id"
      t.integer "parent_id"
      t.binary  "data",      limit: 2147483647
    end
    create_table "gwbbs_docs" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "doc_type"
      t.integer  "parent_id"
      t.text     "content_state"
      t.string   "section_code"
      t.text     "section_name"
      t.integer  "importance"
      t.integer  "one_line_note"
      t.integer  "title_id"
      t.text     "name"
      t.text     "pname"
      t.text     "title"
      t.text     "head",               limit: 16777215
      t.text     "body",               limit: 16777215
      t.text     "note",               limit: 16777215
      t.integer  "category_use"
      t.integer  "category1_id"
      t.integer  "category2_id"
      t.integer  "category3_id"
      t.integer  "category4_id"
      t.text     "keywords"
      t.text     "createdate"
      t.boolean  "creater_admin"
      t.string   "createrdivision_id", limit: 20
      t.text     "createrdivision"
      t.string   "creater_id",         limit: 20
      t.text     "creater"
      t.text     "editdate"
      t.boolean  "editor_admin"
      t.string   "editordivision_id",  limit: 20
      t.text     "editordivision"
      t.string   "editor_id",          limit: 20
      t.text     "editor"
      t.datetime "able_date"
      t.datetime "expiry_date"
      t.integer  "attachmentfile"
      t.string   "form_name"
      t.text     "inpfld_001"
      t.text     "inpfld_002"
      t.text     "inpfld_003"
      t.text     "inpfld_004"
      t.text     "inpfld_005"
      t.text     "inpfld_006"
      t.string   "inpfld_006w"
      t.datetime "inpfld_006d"
      t.text     "inpfld_007"
      t.text     "inpfld_008"
      t.text     "inpfld_009"
      t.text     "inpfld_010"
      t.text     "inpfld_011"
      t.text     "inpfld_012"
      t.text     "inpfld_013"
      t.text     "inpfld_014"
      t.text     "inpfld_015"
      t.text     "inpfld_016"
      t.text     "inpfld_017"
      t.text     "inpfld_018"
      t.text     "inpfld_019"
      t.text     "inpfld_020"
      t.text     "inpfld_021"
      t.text     "inpfld_022"
      t.text     "inpfld_023"
      t.text     "inpfld_024"
      t.text     "inpfld_025"
    end
    create_table "gwbbs_files" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "parent_id"
      t.integer  "title_id"
      t.string   "content_type"
      t.text     "filename"
      t.text     "memo"
      t.integer  "size"
      t.integer  "width"
      t.integer  "height"
      t.integer  "db_file_id"
    end
    create_table "gwbbs_recognizers" do |t|
      t.integer  "unid"
      t.datetime "updated_at"
      t.datetime "created_at"
      t.integer  "title_id"
      t.integer  "parent_id"
      t.integer  "user_id"
      t.string   "code"
      t.text     "name"
      t.datetime "recognized_at"
    end

    # gwfaq
    create_table "gwfaq_categories" do |t|
      t.integer  "unid"
      t.integer  "parent_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.integer  "title_id"
      t.integer  "sort_no"
      t.integer  "level_no"
      t.text     "name"
    end
    create_table "gwfaq_db_files" do |t|
      t.integer "title_id"
      t.integer "parent_id"
      t.binary  "data",      limit: 2147483647
    end
    create_table "gwfaq_docs" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "doc_type"
      t.integer  "parent_id"
      t.text     "content_state"
      t.string   "section_code"
      t.text     "section_name"
      t.integer  "importance"
      t.integer  "one_line_note"
      t.integer  "title_id"
      t.text     "name"
      t.text     "pname"
      t.text     "title"
      t.text     "head",               limit: 16777215
      t.text     "body",               limit: 16777215
      t.text     "note",               limit: 16777215
      t.integer  "category_use"
      t.integer  "category1_id"
      t.integer  "category2_id"
      t.integer  "category3_id"
      t.integer  "category4_id"
      t.text     "keywords"
      t.text     "createdate"
      t.boolean  "creater_admin"
      t.string   "createrdivision_id", limit: 20
      t.text     "createrdivision"
      t.string   "creater_id",         limit: 20
      t.text     "creater"
      t.text     "editdate"
      t.boolean  "editor_admin"
      t.string   "editordivision_id",  limit: 20
      t.text     "editordivision"
      t.string   "editor_id",          limit: 20
      t.text     "editor"
      t.integer  "attachmentfile"
    end
    create_table "gwfaq_files" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "parent_id"
      t.integer  "title_id"
      t.string   "content_type"
      t.text     "filename"
      t.text     "memo"
      t.integer  "size"
      t.integer  "width"
      t.integer  "height"
      t.integer  "db_file_id"
    end
    create_table "gwfaq_recognizers", force: true do |t|
      t.integer  "unid"
      t.datetime "updated_at"
      t.datetime "created_at"
      t.integer  "title_id"
      t.integer  "parent_id"
      t.integer  "user_id"
      t.string   "code"
      t.text     "name"
      t.datetime "recognized_at"
    end

    # gwqa
    create_table "gwqa_categories" do |t|
      t.integer  "unid"
      t.integer  "parent_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.integer  "title_id"
      t.integer  "sort_no"
      t.integer  "level_no"
      t.text     "name"
    end
    create_table "gwqa_db_files" do |t|
      t.integer "title_id"
      t.integer "parent_id"
      t.binary  "data",      limit: 2147483647
    end
    create_table "gwqa_docs" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "doc_type"
      t.integer  "parent_id"
      t.text     "content_state"
      t.string   "section_code"
      t.text     "section_name"
      t.integer  "importance"
      t.integer  "one_line_note"
      t.integer  "title_id"
      t.text     "name"
      t.text     "pname"
      t.text     "title"
      t.text     "head",               limit: 16777215
      t.text     "body",               limit: 16777215
      t.text     "note",               limit: 16777215
      t.integer  "category_use"
      t.integer  "category1_id"
      t.integer  "category2_id"
      t.integer  "category3_id"
      t.integer  "category4_id"
      t.text     "keywords"
      t.text     "createdate"
      t.boolean  "creater_admin"
      t.string   "createrdivision_id", limit: 20
      t.text     "createrdivision"
      t.string   "creater_id",         limit: 20
      t.text     "creater"
      t.text     "editdate"
      t.boolean  "editor_admin"
      t.string   "editordivision_id",  limit: 20
      t.text     "editordivision"
      t.string   "editor_id",          limit: 20
      t.text     "editor"
      t.datetime "expiry_date"
      t.integer  "attachmentfile"
      t.integer  "answer_count"
      t.text     "inpfld_001"
      t.text     "inpfld_002"
      t.datetime "latest_answer"
    end
    create_table "gwqa_files" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "parent_id"
      t.integer  "title_id"
      t.string   "content_type"
      t.text     "filename"
      t.text     "memo"
      t.integer  "size"
      t.integer  "width"
      t.integer  "height"
      t.integer  "db_file_id"
    end
    create_table "gwqa_recognizers", force: true do |t|
      t.integer  "unid"
      t.datetime "updated_at"
      t.datetime "created_at"
      t.integer  "title_id"
      t.integer  "parent_id"
      t.integer  "user_id"
      t.string   "code"
      t.text     "name"
      t.datetime "recognized_at"
    end

    # doclibrary
    create_table "doclibrary_categories" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.integer  "title_id"
      t.integer  "parent_id"
      t.integer  "sort_no"
      t.integer  "level_no"
      t.text     "wareki"
      t.integer  "nen"
      t.integer  "gatsu"
      t.integer  "sono"
      t.integer  "sono2"
      t.string   "filename"
      t.string   "note_id"
      t.text     "createdate"
      t.boolean  "creater_admin"
      t.string   "createrdivision_id", limit: 20
      t.text     "createrdivision"
      t.string   "creater_id",         limit: 20
      t.text     "creater"
      t.text     "editdate"
      t.boolean  "editor_admin"
      t.string   "editordivision_id",  limit: 20
      t.text     "editordivision"
      t.string   "editor_id",          limit: 20
      t.text     "editor"
    end
    create_table "doclibrary_db_files" do |t|
      t.integer "title_id"
      t.integer "parent_id"
      t.binary  "data",      limit: 2147483647
    end
    create_table "doclibrary_docs" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "doc_type"
      t.integer  "parent_id"
      t.text     "content_state"
      t.string   "section_code"
      t.text     "section_name"
      t.integer  "importance"
      t.integer  "one_line_note"
      t.integer  "title_id"
      t.text     "name"
      t.text     "pname"
      t.text     "title"
      t.text     "head",               limit: 16777215
      t.text     "body",               limit: 16777215
      t.text     "note",               limit: 16777215
      t.integer  "category_use"
      t.integer  "category1_id"
      t.integer  "category2_id"
      t.integer  "category3_id"
      t.integer  "category4_id"
      t.text     "keywords"
      t.text     "createdate"
      t.boolean  "creater_admin"
      t.string   "createrdivision_id", limit: 20
      t.text     "createrdivision"
      t.string   "creater_id",         limit: 20
      t.text     "creater"
      t.text     "editdate"
      t.boolean  "editor_admin"
      t.string   "editordivision_id",  limit: 20
      t.text     "editordivision"
      t.string   "editor_id",          limit: 20
      t.text     "editor"
      t.datetime "expiry_date"
      t.integer  "attachmentfile"
      t.string   "form_name"
      t.text     "inpfld_001"
      t.integer  "inpfld_002"
      t.integer  "inpfld_003"
      t.integer  "inpfld_004"
      t.integer  "inpfld_005"
      t.integer  "inpfld_006"
      t.text     "inpfld_007"
      t.text     "inpfld_008"
      t.text     "inpfld_009"
      t.text     "inpfld_010"
      t.text     "inpfld_011"
      t.text     "inpfld_012"
      t.text     "notes_001"
      t.text     "notes_002"
      t.text     "notes_003"
    end
    create_table "doclibrary_files" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "parent_id"
      t.integer  "title_id"
      t.string   "content_type"
      t.text     "filename"
      t.text     "memo"
      t.integer  "size"
      t.integer  "width"
      t.integer  "height"
      t.integer  "db_file_id"
    end
    create_table "doclibrary_folder_acls" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.integer  "folder_id"
      t.integer  "title_id"
      t.integer  "acl_flag"
      t.integer  "acl_section_id"
      t.string   "acl_section_code"
      t.text     "acl_section_name"
      t.integer  "acl_user_id"
      t.string   "acl_user_code"
      t.text     "acl_user_name"
    end
    create_table "doclibrary_folders" do |t|
      t.integer  "unid"
      t.integer  "parent_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.integer  "title_id"
      t.integer  "sort_no"
      t.integer  "level_no"
      t.integer  "children_size"
      t.integer  "total_children_size"
      t.text     "name"
      t.text     "memo"
      t.text     "readers"
      t.text     "readers_json"
      t.text     "reader_groups"
      t.text     "reader_groups_json"
      t.datetime "docs_last_updated_at"
    end
    create_table "doclibrary_group_folders" do |t|
      t.integer  "unid"
      t.integer  "parent_id"
      t.text     "state"
      t.text     "use_state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.integer  "title_id"
      t.integer  "sort_no"
      t.integer  "level_no"
      t.integer  "children_size"
      t.integer  "total_children_size"
      t.string   "code"
      t.text     "name"
      t.integer  "sysgroup_id"
      t.integer  "sysparent_id"
      t.text     "readers"
      t.text     "readers_json"
      t.text     "reader_groups"
      t.text     "reader_groups_json"
      t.datetime "docs_last_updated_at"
    end
    create_table "doclibrary_recognizers" do |t|
      t.integer  "unid"
      t.datetime "updated_at"
      t.datetime "created_at"
      t.integer  "title_id"
      t.integer  "parent_id"
      t.integer  "user_id"
      t.string   "code"
      t.text     "name"
      t.datetime "recognized_at"
    end

    # digitallibrary
    create_table "digitallibrary_db_files" do |t|
      t.integer "title_id"
      t.integer "parent_id"
      t.binary  "data",      limit: 2147483647
    end
    create_table "digitallibrary_docs" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.integer  "parent_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "doc_type"
      t.integer  "display_order"
      t.integer  "doc_alias"
      t.integer  "title_id"
      t.integer  "chg_parent_id"
      t.integer  "sort_no"
      t.float    "seq_no",             limit: 24
      t.integer  "order_no"
      t.string   "seq_name"
      t.integer  "level_no"
      t.string   "section_code"
      t.text     "section_name"
      t.text     "name"
      t.text     "title"
      t.text     "body",               limit: 16777215
      t.text     "note",               limit: 16777215
      t.integer  "category1_id"
      t.integer  "category2_id"
      t.integer  "category3_id"
      t.integer  "category4_id"
      t.text     "keywords",           limit: 16777215
      t.text     "createdate"
      t.boolean  "creater_admin"
      t.string   "createrdivision_id", limit: 20
      t.text     "createrdivision"
      t.string   "creater_id",         limit: 20
      t.text     "creater"
      t.text     "editdate"
      t.boolean  "editor_admin"
      t.string   "editordivision_id",  limit: 20
      t.text     "editordivision"
      t.string   "editor_id",          limit: 20
      t.text     "editor"
      t.text     "readers"
      t.text     "readers_json"
      t.text     "notes_001"
      t.integer  "attachmentfile"
    end
    create_table "digitallibrary_files" do |t|
      t.integer  "unid"
      t.integer  "content_id"
      t.text     "state"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.datetime "recognized_at"
      t.datetime "published_at"
      t.datetime "latest_updated_at"
      t.integer  "parent_id"
      t.integer  "title_id"
      t.string   "content_type"
      t.text     "filename"
      t.text     "memo"
      t.integer  "size"
      t.integer  "width"
      t.integer  "height"
      t.integer  "db_file_id"
    end
    create_table "digitallibrary_recognizers" do |t|
      t.integer  "unid"
      t.datetime "updated_at"
      t.datetime "created_at"
      t.integer  "title_id"
      t.integer  "parent_id"
      t.integer  "user_id"
      t.string   "code"
      t.text     "name"
      t.datetime "recognized_at"
    end
  end
end
